import { ColDef, ColGroupDef } from "ag-grid-community";

export const quoteColDefs:(ColDef|ColGroupDef)[] = [
    {field: 'symbol', headerName:'Ticker', singleClickEdit:true, editable: true},
    {field: 'assetType', headerName:'Asset Type'},
    /*{field: 'assetMainType', headerName:'Main Asset Type'},*/
    {field: 'cusip', headerName:'Cusip'},
    {field: 'description', headerName:'Descrption'},
    {field: 'bidPrice', headerName:'Bid Price', type:'rightAligned'},
    {field: 'bidSize', headerName:'Bid Size', type:'rightAligned'},
    {field: 'bidId', headerName:'Bid Id'},
    {field: 'askPrice', headerName:'Ask Price', type:'rightAligned'},
    {field: 'askSize', headerName:'Ask Size', type:'rightAligned'},
    {field: 'askId', headerName:'Ask Id'},
    {field: 'lastPrice', headerName:'Last Price', type:'rightAligned'},
    {field: 'lastSize', headerName:'Last Size', type:'rightAligned'},
    {field: 'lastId', headerName:'Last Id'},
    {field: 'openPrice', headerName:'Open Price', type:'rightAligned'},
    {field: 'highPrice', headerName:'High Price', type:'rightAligned'},
    {field: 'lowPrice', headerName:'Low Price', type:'rightAligned'},
    {field: 'bidTick', headerName:'Bid Tick'},
    {field: 'closePrice', headerName:'Close Price', type:'rightAligned'},
    {field: 'netChange', headerName:'Net Change', type:'rightAligned'},
    {field: 'totalVolume', headerName:'Total Volumne', type:'rightAligned'},
    {field: 'quoteTimeInLong', headerName:'Quote Time'},
    {field: 'tradeTimeInLong', headerName:'Trade Time'},
    {field: 'mark', headerName:'Mark'},
    {field: 'exchange', headerName:'Exchange'},
    {field: 'exchangeName', headerName:'Exch Name'},
    {field: 'marginable', headerName:'Marginable?'},
    {field: 'shortable', headerName:'Shortable?'},
    {field: 'volatility', headerName:'Volatility', type:'rightAligned'},
    {field: 'digits', headerName:'Digits'},
    {field: 'WkHigh', headerName:'52 Week High', type:'rightAligned'},
    {field: 'WkLow', headerName:'52 Week Low', type:'rightAligned'},
    {field: 'nAV', headerName:'Net Asset Value'},
    {field: 'peRatio', headerName:'P/E Ratio'},
    {field: 'divAmount', headerName:'Dividend Amt'},
    {field: 'divYield', headerName:'Divdend Yield'},
    {field: 'divDate', headerName:'Dividend Date'},
    {field: 'securityStatus', headerName:'Security Status'},
    {field: 'regularMarketLastPrice', headerName:'Mkt Last Price'},
    {field: 'regularMarketLastSize', headerName:'Mkt Last Size'},
    {field: 'regularMarketNetChange', headerName:'Mkt Last Net Chg'},
    {field: 'regularMarketTradeTimeInLong', headerName:'Mkt Trade Time'},
    {field: 'netPercentChangeInDouble', headerName:'Net Percent Change'},
    {field: 'markChangeInDouble', headerName:'Mark Change'},
    {field: 'markPercentChangeInDouble', headerName:'Mark Percentage Change'},
    {field: 'regularMarketPercentChangeInDouble', headerName:'Reg Mkt Percent Change'},
    {field: 'delayed', headerName:'Delayed?'}
]
