export const tradeColDefs = [
    {field:'assetType', headerName:'Asset', cellStyle: {fontSize: '50%'}}, 
    {field:'cusip', headerName:'Cusip', cellStyle: {fontSize: '50%'}}, 
    {field:'symbol', headerName:'Symbol', cellStyle: {fontSize: '50%'}},
    
    {field:'amount', headerName:'Amount', cellStyle: {fontSize: '50%'}},
    {field:'price', headerName:'Price', cellStyle: {fontSize: '50%'}},
    {field:'cost', headerName:'Cost', cellStyle: {fontSize: '50%'}},
    {field:'accountId', headerName:'Account Id', cellStyle: {fontSize: '50%'}},
    {field:'instruction', headerName:'Instruction', cellStyle: {fontSize: '50%'}},
    
    {field:'type', headerName:'Type', cellStyle: {fontSize: '50%'}},
    {field:'subAccount', headerName:'Sub Acc', cellStyle: {fontSize: '50%'}},
    {field:'settlementDate', headerName:'Settlement Date', cellStyle: {fontSize: '50%'}},
    {field:'orderId', headerName:'Order Id', cellStyle: {fontSize: '50%'}},
    {field:'netAmount', headerName:'Net Amt', cellStyle: {fontSize: '50%'}},
    {field:'transactionDate', headerName:'Transaction Date', cellStyle: {fontSize: '50%'}},
    {field:'orderDate', headerName:'Order Date', cellStyle: {fontSize: '50%'}},
    {field:'transactionSubType', headerName:'Trans Sub Type', cellStyle: {fontSize: '50%'}},
    {field:'transactionId', headerName:'Trans Id', cellStyle: {fontSize: '50%'}},
    {field:'cashBalanceEffectFlag', headerName:'Cash Bal Effect Flag', cellStyle: {fontSize: '50%'}},
    {field:'description', headerName:'Desc', cellStyle: {fontSize: '50%'}},
    
    {field:'rFee', headerName:'R Fee', cellStyle: {fontSize: '50%'}},
    {field:'additionalFee', headerName:'Addnl Fee', cellStyle: {fontSize: '50%'}},
    {field:'cdscFee', headerName:'CDSC Fee', cellStyle: {fontSize: '50%'}},
    {field:'regFee', headerName:'Reg Fee', cellStyle: {fontSize: '50%'}},
    {field:'otherCharges', headerName:'Other Chgs', cellStyle: {fontSize: '50%'}},
    {field:'commission', headerName:'Commision', cellStyle: {fontSize: '50%'}},
    {field:'optRegFee', headerName:'Opt Reg Fee', cellStyle: {fontSize: '50%'}},
    {field:'secFee', headerName:'Sec Fee', cellStyle: {fontSize: '50%'}},  
]
