export const types = {
   REDUX_WEBSOCKET_MESSAGE: 'REDUX_WEBSOCKET::MESSAGE',
    INIT_TICKER: 'INIT_TICKER',
    NEW_TICKER: 'NEW_TICKER',
    DELETE_TICKER: 'DELETE_TICKER',
    SELECT_TICKER: 'SELECT_TICKER',
  };